/*Login Actions*/
export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const PASSWORD2_CHANGED = "PASSWORD2_CHANGED";
export const LOGIN_USER_LOAD = "LOGIN_USER_LOAD";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_LOGGED_IN = "LOGIN_USER_LOGGED_IN";
export const LOGIN_USER_LOGGED = "LOGIN_USER_LOGGED";

/*SIGNUP Actions*/

export const SIGNUP_PASS_V = "SIGNUP_PASS_V";